diff_drive_controller:
  type: diff_drive_controller/DiffDriveController

  left_wheel_names: ["left_wheel_joint"]
  right_wheel_names: ["right_wheel_joint"]

  wheel_separation: 0.05
  wheel_radius: 0.025

  use_stamped_vel: false
  base_frame_id: robot2/base_link
  odom_frame_id: robot2/odom

  publish_rate: 30.0
